Q1. What is Min-Max scaling, and how is it used in data preprocessing? Provide an example to illustrate its  application. 


It transforms features by scaling each feature to a given range, which is generally [0,1], or [-1,-1] in case of negative values

In [4]:
import seaborn as sns

In [5]:
df = sns.load_dataset('taxis')

In [6]:
df.head()

pickup             dropoff  passengers  distance  fare   tip  \
0 2019-03-23 20:21:09 2019-03-23 20:27:24           1      1.60   7.0  2.15   
1 2019-03-04 16:11:55 2019-03-04 16:19:00           1      0.79   5.0  0.00   
2 2019-03-27 17:53:01 2019-03-27 18:00:25           1      1.37   7.5  2.36   
3 2019-03-10 01:23:59 2019-03-10 01:49:51           1      7.70  27.0  6.15   
4 2019-03-30 13:27:42 2019-03-30 13:37:14           3      2.16   9.0  1.10   

   tolls  total   color      payment            pickup_zone  \
0    0.0  12.95  yellow  credit card        Lenox Hill West   
1    0.0   9.30  yellow         cash  Upper West Side South   
2    0.0  14.16  yellow  credit card          Alphabet City   
3    0.0  36.95  yellow  credit card              Hudson Sq   
4    0.0  13.40  yellow  credit card           Midtown East   

            dropoff_zone pickup_borough dropoff_borough  
0    UN/Turtle Bay South      Manhattan       Manhattan  
1  Upper West Side South      Manhattan       Manhattan  
2           West Village      Manhattan       Manhattan  
3         Yorkville West      Manhattan       Manhattan  
4         Yorkville West      Manhattan       Manhattan

In [7]:
from sklearn.preprocessing import MinMaxScaler

In [8]:
min_max = MinMaxScaler()

In [9]:
min_max.fit_transform(df[['distance','fare','tip']])

array([[0.04359673, 0.04026846, 0.06475904],
       [0.02152589, 0.02684564, 0.        ],
       [0.0373297 , 0.04362416, 0.07108434],
       ...,
       [0.11280654, 0.10067114, 0.        ],
       [0.03051771, 0.03355705, 0.        ],
       [0.10490463, 0.09395973, 0.10120482]])

In [10]:
min_max.transform([[1,2,3]]) # for new data

/opt/conda/lib/python3.10/site-packages/sklearn/base.py:409: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


array([[0.02724796, 0.00671141, 0.09036145]])

Application : The MinMax Scaler is a variant to normalize the training data of a Machine Learning model, i.e. to bring the numerical values to a uniform scale. This leads to the model learning and converging faster since the gradient changes uniformly and does not make large jumps due to the different scales.

Q2. What is the Unit Vector technique in feature scaling, and how does it differ from Min-Max scaling?  Provide an example to illustrate its application. 


Unit Vector Scaling technique is done considering the whole feature vector to be of unit length,Unit vector scaling means dividing each component by the Euclidean length of the vector (L2 Norm),Unit Vector technique produces values of range [0,1].

In [11]:
import seaborn as sns

In [12]:
df = sns.load_dataset('iris')

In [13]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [14]:
from sklearn.preprocessing import normalize

In [15]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [16]:
normalize(df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']])

array([[0.80377277, 0.55160877, 0.22064351, 0.0315205 ],
       [0.82813287, 0.50702013, 0.23660939, 0.03380134],
       [0.80533308, 0.54831188, 0.2227517 , 0.03426949],
       [0.80003025, 0.53915082, 0.26087943, 0.03478392],
       [0.790965  , 0.5694948 , 0.2214702 , 0.0316386 ],
       [0.78417499, 0.5663486 , 0.2468699 , 0.05808704],
       [0.78010936, 0.57660257, 0.23742459, 0.0508767 ],
       [0.80218492, 0.54548574, 0.24065548, 0.0320874 ],
       [0.80642366, 0.5315065 , 0.25658935, 0.03665562],
       [0.81803119, 0.51752994, 0.25041771, 0.01669451],
       [0.80373519, 0.55070744, 0.22325977, 0.02976797],
       [0.786991  , 0.55745196, 0.26233033, 0.03279129],
       [0.82307218, 0.51442011, 0.24006272, 0.01714734],
       [0.8025126 , 0.55989251, 0.20529392, 0.01866308],
       [0.81120865, 0.55945424, 0.16783627, 0.02797271],
       [0.77381111, 0.59732787, 0.2036345 , 0.05430253],
       [0.79428944, 0.57365349, 0.19121783, 0.05883625],
       [0.80327412, 0.55126656,

In [17]:
import pandas as pd

In [18]:
pd.DataFrame(df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']],columns =[ 'sepal_length', 'sepal_width', 'petal_length', 'petal_width'])

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

Q3. What is PCA (Principle Component Analysis), and how is it used in dimensionality reduction? Provide an  example to illustrate its application. 


PCA stands for principle component analysis


Principal Component Analysis (PCA) is a powerful technique used in data analysis, particularly for reducing the dimensionality of datasets while preserving crucial information.

example: in the dataset of house , features  like no.rooms , house size . Now we want only one feature instead of two. First we Draw a graph(x = no.rooms , y= house size) and draw a line such that we get max information. Rest of datapoints we have to project them onto that line and we get 1D plane

In [1]:
from sklearn.decomposition import PCA
import numpy as np

# Sample data
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Initialize PCA with the number of components you want
pca = PCA(n_components=2)  # You can change the number of components as needed

# Fit PCA on the data
pca.fit(data)

# Transform the data to the new feature space
transformed_data = pca.transform(data)

# Explained variance ratio
explained_variance_ratio = pca.explained_variance_ratio_

print("Original data:\n", data)
print("\nTransformed data:\n", transformed_data)
print("\nExplained Variance Ratio:", explained_variance_ratio)


Original data:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Transformed data:
 [[-5.19615242e+00 -1.33226763e-15]
 [ 0.00000000e+00  0.00000000e+00]
 [ 5.19615242e+00  1.33226763e-15]]

Explained Variance Ratio: [1.00000000e+00 2.43475588e-33]


In [1]:
from sklearn.decomposition import PCA
import numpy as np

# Sample data
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Initialize PCA with the number of components you want
pca = PCA(n_components=2)  # You can change the number of components as needed

# Fit PCA on the data
pca.fit(data)

# Transform the data to the new feature space
transformed_data = pca.transform(data)

# Explained variance ratio
explained_variance_ratio = pca.explained_variance_ratio_

print("Original data:\n", data)
print("\nTransformed data:\n", transformed_data)
print("\nExplained Variance Ratio:", explained_variance_ratio)


Original data:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Transformed data:
 [[-5.19615242e+00 -1.33226763e-15]
 [ 0.00000000e+00  0.00000000e+00]
 [ 5.19615242e+00  1.33226763e-15]]

Explained Variance Ratio: [1.00000000e+00 2.43475588e-33]


Q4. What is the relationship between PCA and Feature Extraction, and how can PCA be used for Feature  Extraction? Provide an example to illustrate this concept. 

Feature extraction is the process of selecting and extracting the most important feature from raw data.

It has three techniquies: 1.Feature Scaling 2. feature selection 3.PCA

Basically PCA(Principle component analysis) is the type of feature extraction.

example: in the dataset of house , features  like no.rooms , house size . Now we want only one feature instead of two. First we Draw a graph(x = no.rooms , y= house size) and draw a line such that we get max information. Rest of datapoints we have to project them onto that line and we get 1D plane

In [2]:
from sklearn.decomposition import PCA
import numpy as np

# Sample data
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Initialize PCA with the number of components you want
pca = PCA(n_components=2)  # You can change the number of components as needed

# Fit PCA on the data
pca.fit(data)

# Transform the data to the new feature space
transformed_data = pca.transform(data)

# Explained variance ratio
explained_variance_ratio = pca.explained_variance_ratio_

print("Original data:\n", data)
print("\nTransformed data:\n", transformed_data)
print("\nExplained Variance Ratio:", explained_variance_ratio)


Original data:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Transformed data:
 [[-5.19615242e+00 -1.33226763e-15]
 [ 0.00000000e+00  0.00000000e+00]
 [ 5.19615242e+00  1.33226763e-15]]

Explained Variance Ratio: [1.00000000e+00 2.43475588e-33]


Q5. You are working on a project to build a recommendation system for a food delivery service. The dataset  contains features such as price, rating, and delivery time. Explain how you would use Min-Max scaling to  preprocess the data. 

Min-Max scaling is a method used in preprocessing data to scale numeric features to a specific range, typically between 0 and 1. It's particularly useful when dealing with features that have different scales or ranges, ensuring that all features contribute equally to the analysis. In the context of building a recommendation system for a food delivery service using features like price, rating, and delivery time, 

Understand the Data: First, you need to understand the range and distribution of your features (price, rating, delivery time). Check for any outliers or extreme values that might significantly affect the scaling process.

Normalize Features using Min-Max Scaling:

For each feature (price, rating, delivery time), calculate the minimum and maximum values within the dataset.

Utilize Scaled Data: Use the scaled features (price, rating, delivery time) in your recommendation system model. Scaled features ensure that each feature contributes fairly to the recommendation process, regardless of their original scales.

Q6. You are working on a project to build a model to predict stock prices. The dataset contains many  features, such as company financial data and market trends. Explain how you would use PCA to reduce the  dimensionality of the dataset. 


Understanding the Dataset:

Analyze the dataset thoroughly to comprehend the nature of the features. Determine which features are relevant to predicting stock prices and understand their interrelationships.

Data Preprocessing:

Clean the dataset by handling missing values, normalizing or standardizing features if necessary, and encoding categorical variables.

Implement PCA:

Select the subset of features that you want to use for predicting stock prices. These can include various financial metrics, market indicators, etc.

Analyzing Results:

Examine the explained variance ratio to understand how much variance is retained by each principal component. This helps in determining the optimal number of components to use.

Q7. For a dataset containing the following values: [1, 5, 10, 15, 20], perform Min-Max scaling to transform the  values to a range of -1 to 1. 


In [12]:
import numpy as np

# Original dataset
data = np.array([1, 5, 10, 15, 20])

# Min-Max scaling
min_val = np.min(data)
max_val = np.max(data)

# Standard Min-Max scaling formula
scaled_data = (data - min_val) / (max_val - min_val)

# Scaling to the range of -1 to 1
scaled_to_range = 2 * scaled_data - 1

print("Original data:", data)
print("Data scaled to range -1 to 1:", scaled_to_range)


Original data: [ 1  5 10 15 20]
Data scaled to range -1 to 1: [-1.         -0.57894737 -0.05263158  0.47368421  1.        ]


Q8. For a dataset containing the following features: [height, weight, age, gender, blood pressure], perform  Feature Extraction using PCA. How many principal components would you choose to retain, and why?

Deciding the number of principal components to retain during PCA involves a trade-off between reducing dimensionality and retaining sufficient information. The choice often relies on the explained variance ratio captured by these principal components.

Feature Extraction with PCA:

Extract the features ['height', 'weight', 'age', 'gender', 'blood_pressure'] from your dataset.
Standardization:

Standardize the data using StandardScaler() to have zero mean and unit variance for each feature. This step is essential for PCA.
PCA Initialization and Fitting:

Initialize PCA and fit it to the standardized data. You can set the number of principal components by specifying the n_components parameter. Here, it's set to 3 for demonstration purposes; you can adjust it based on your requirements.
Transform Data:

Transform the standardized data into the principal components space using the fitted PCA model.
Conversion to DataFrame (Optional):

Convert the transformed data into a DataFrame for further analysis or modeling purposes.
Explained Variance Ratio:

The explained_variance_ratio_ attribute of the PCA model gives the proportion of variance explained by each principal component.